language: node_js
node_js:
  - "iojs"
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "node"

before_install:
  - yarn add -g pm2

after_script:
  - pm2 logs all --nostream --lines 10000
  - pm2 delete all
  - pm2 kill
